name: schnorr_auth_app
description: "Applicazione mobile che implmenta il protocollo d'identificazione di Schnorr"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  mobile_scanner: ^7.0.1
  web_socket_channel: ^2.4.0
  device_info_plus: ^11.5.0
  path_provider: ^2.1.5 
  path: ^1.9.1
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21